# Generated by Django 5.1 on 2025-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dockerhost_dockercontainer_dockercontainermetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainer',
            name='container_id',
            field=models.CharField(max_length=255, verbose_name='ID контейнера'),
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID образа'),
        ),
    ]
